### PR TITLE
Feature/my sql maker test

### PR DESCRIPTION
**Pull request by mstrYoda**

### CODE REVIEW

**Comment by mstrYoda** [comment]
This pr can be merge after #34 merges.

**Comment by ccleve** [comment]
#34 has been merged. You might want to revisit this one, make all the versions consistent.

**Comment by mstrYoda** [comment]
@ccleve Updated 👍

**Comment by ccleve** [comment]
Remove the changes to the README and the pom and I'll do the merge.

**Comment by mstrYoda** [comment]
> Remove the changes to the README and the pom and I'll do the merge.

Done. I surprised to existence of that changes even though I did not made any of them.

**Pull request merged**
