### PR TITLE
Error columnDefinition logic(@Column(columnDefinition="TEXT") doesn't work)

### PR DESCRIPTION
**Pull request by zhaodice**
why execute buf.append(null) when columnAnnot.columnDefinition()==null ?

### CODE REVIEW

**Comment by ccleve** [comment]
Could you give an example of the problem that this PR fixes?

**Comment by MagnetiteMC** [comment]
> Could you give an example of the problem that this PR fixes?

I came across the same issue experienced by this user. Anything put in columnDefinition will not work because it's checking if the column definition is null instead of not null. For example, this is completely ignored.
image

It's just as simple as change the == to != like in the pull request. I've confirmed this myself and made a temporary fix by just making a SqlMaker that extends StandardSqlMaker, and overrides the getCreateTableSql method. Then I used db.setSqlMaker() to use my custom one. Everything worked perfectly after that.

**Comment by ccleve** [comment]
@MagnetiteMC  Ok, I see it now. I simply changed == to !=, rather than do it as he did in the pr, to give the dev more flexibility to specify the entire column definition. Let me know if this works for you.

**Comment by MagnetiteMC** [comment]
> @MagnetiteMC Ok, I see it now. I simply changed == to !=, rather than do it as he did in the pr, to give the dev more flexibility to specify the entire column definition. Let me know if this works for you.

@ccleve My bad for the late reply. Everything is fixed after using your change. This pull request can be closed. Thank you for the fix!

**Pull request closed without merging**
