### PR TITLE
Adding support for multiple primary keys as a composite key to address #77

### PR DESCRIPTION
**Pull request by TheTurkeyDev**
Before I sink more than a few minutes into this, on paper this solution should work. If you are ok with proceeding with adding this feature and completing this PR I will write tests around this and more confidently confirm this does work.

I am open to all suggestions. I do know that changing primaryKeyName to primaryKeyNames and making it an array list does potentially break existing code, but I feel its a minimal change and is easy enough to update existing code.

Let me know what you think

Addresses #77

### CODE REVIEW

**Comment by ccleve** [comment]
This might be a good addition, but we should have a look at the JPA standard first. Here's what I found:

https://www.google.com/search?client=firefox-b-1-d&q=javax.persistence+multiple+primary+keys

I'm not clear on why @IdClass should be necessary. Just adding @Id to each column should be enough. But I'm sure they had a reason for it, and we should understand the reason before we make any big changes.

**Comment by TheTurkeyDev** [comment]
Found this write up explaining it a bit https://www.oracle.com/technical-resources/articles/javaee/marx-jpa.html Makes somewhat sense (not sure If I would have done it), but I do feel that it's a bit extra especially since the values are still marked with @Id in the embed class. Also they use "prefer" when talking about it, so it doesn't sound like a requirement? I like this solution more, but I do agree with following standards, so if it truly is one this should be switched to it

**Comment by ccleve** [comment]
I'm not convinced by the logic in that article. I think it's better to just have multiple @Id annotations and be done with it. This is not incompatible with JPA, and if in the future we want to support @EmbeddedId we can just do it without any backward compatibility problem.

**Comment by TheTurkeyDev** [comment]
Gotcha. I do think this solution is very minimal and honestly can't find much beyond those Java docs in terms of standards for JPA. Is this a green light to continue with this PR?

**Comment by ccleve** [comment]
Yes

**Comment by TheTurkeyDev** [comment]
Fixed a bug and added tests around this. The upserts fail locally for me, but the generated SQL is correct & the tests that you already have around the upserts fail for me locally as well, so I must have some issue locally with them since they do work in the current version.

Let me know what you think

**Comment by ccleve** [comment]
Everything looks good. I ran your tests against local h2 and postgres installs, and they worked except for the upserts because I haven't implemented upserts for either. 

I also ran it against a local mysql install and everything worked perfectly, including the upserts.

Merging...

**Comment by TheTurkeyDev** [comment]
Thanks! Will you be planning to push this out to the maven repository? Just makes my life easier than having to add it locally

**Comment by ccleve** [comment]
Done. v1.0.5 should appear on Maven Central shortly.

**Pull request merged**
